server{
    listen 80;
    index index.php index.html;
    server_name localhost;
    root /var/www/html/public;

    location / {
        try_files $uri $uri/ /index.php?$query_string;

    }

    location ~ \.php$ {
        fastcgi_pass app:9000; #redirige al puerto 9000
        # define archivo por defecto si se accede a un directorio PHP
        fastcgi_index index.php;

        #indica a php-fpm la ruta en el sistema donde se guarda el .php a ejecutar
        fastcgi_param SCRIPT_FILENAME $document_root$fastcgi_script_name;

        #cargamos variables estandar del protocolo FascCGI (http, get, post, IP cliente ...)
        include fastcgi_params;
    }
}